"use client";

import { useState } from "react";
import {
  CalendarDays,
  User,
  PlayCircle,
  CheckCircle2,
  Pencil,
  Trash2,
  Flag,
  RotateCcw,
  Sparkles,
} from "lucide-react";
import { StatusBadge, PriorityBadge } from "@/components/common/Badge";
import Button from "@/components/common/Button";
import WhatsAppButton from "@/components/whatsapp/WhatsAppButton";
import { patchData } from "@/lib/client";
import { formatDate, daysRemaining } from "@/lib/utils";
import { generateDocumentRequestMessage } from "@/lib/whatsappMessages";

export default function ComplianceCard({ record, onEdit, onDelete, onStatusChange }) {
  const [status, setStatus] = useState(record.status);
  const [updating, setUpdating] = useState(false);
  const [error, setError] = useState("");
  const [nextScheduled, setNextScheduled] = useState(null);

  const days = daysRemaining(record.dueDate);
  const isLate = days !== null && days < 0;
  const isSoon = days !== null && days >= 0 && days <= 3;
  const isCompleted = status === "COMPLETED";

  const changeStatus = async (next) => {
    if (updating) return;
    setError("");
    setNextScheduled(null);
    const prev = status;
    setStatus(next); // optimistic — card reacts instantly
    setUpdating(true);
    try {
      const updated = await patchData(`/api/compliance/${record._id}`, { status: next });
      if (updated?.nextScheduled) setNextScheduled(updated.nextScheduled);
      else setNextScheduled(null);
      onStatusChange && onStatusChange();
    } catch (err) {
      setStatus(prev); // revert on failure
      setError(err.message || "Could not update. Please try again.");
    } finally {
      setUpdating(false);
    }
  };

  return (
    <div className={`card p-3.5 sm:p-4 flex flex-col transition-opacity ${isCompleted ? "opacity-75" : ""}`}>
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2 sm:gap-2.5 min-w-0">
          <div className={`h-8 w-8 sm:h-9 sm:w-9 rounded-lg flex items-center justify-center text-xs font-semibold shrink-0 ${
            isCompleted
              ? "bg-emerald-50 text-emerald-600"
              : isLate
              ? "bg-rose-50 text-rose-600"
              : isSoon
              ? "bg-amber-50 text-amber-600"
              : "bg-slate-100 text-slate-500"
          }`}>
            {isCompleted ? <CheckCircle2 size={16} /> : days !== null ? `${days}d` : "—"}
          </div>
          <div className="min-w-0">
            <h3 className="font-semibold text-slate-900 text-sm sm:text-base leading-snug truncate">
              {record.clientId?.name || "Client"}
            </h3>
            <p className="text-[11px] sm:text-xs text-slate-400 truncate flex items-center gap-1">
              {record.type}
              {record.autoGenerated && (
                <span title="Auto-scheduled after the previous filing was completed" className="inline-flex items-center gap-0.5 text-[10px] font-medium text-indigo-500">
                  <Sparkles size={10} /> auto
                </span>
              )}
            </p>
          </div>
        </div>
        <div className="flex gap-0.5 shrink-0">
          {onEdit && (
            <button onClick={() => onEdit(record)} disabled={updating} className="p-2 sm:p-1.5 rounded-lg text-slate-400 hover:text-brand-700 hover:bg-brand-50 transition-colors disabled:opacity-50" aria-label="Edit">
              <Pencil size={15} />
            </button>
          )}
          {onDelete && (
            <button onClick={() => onDelete(record)} disabled={updating} className="p-2 sm:p-1.5 rounded-lg text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition-colors disabled:opacity-50" aria-label="Delete">
              <Trash2 size={15} />
            </button>
          )}
        </div>
      </div>

      <div className="flex flex-wrap items-center gap-1.5 mt-3">
        <StatusBadge status={status} />
        <PriorityBadge priority={record.priority} />
      </div>

      {/* Completed confirmation */}
      {isCompleted && (
        <div className="mt-3 rounded-lg bg-emerald-50 border border-emerald-100 px-3 py-2.5 text-xs text-emerald-800">
          <p className="font-semibold flex items-center gap-1.5">
            <CheckCircle2 size={13} /> Filing completed{record.completedAt ? ` on ${formatDate(record.completedAt)}` : ""}
          </p>
          {nextScheduled ? (
            <p className="mt-0.5 text-emerald-700">Next occurrence scheduled for {formatDate(nextScheduled)}.</p>
          ) : record.recurrence && record.recurrence !== "NONE" ? (
            <p className="mt-0.5 text-emerald-700">Next occurrence already on your list.</p>
          ) : null}
        </div>
      )}

      {error && (
        <div className="mt-3 rounded-lg bg-rose-50 border border-rose-100 px-3 py-2 text-xs text-rose-700">
          {error}
        </div>
      )}

      <div className="mt-3 sm:mt-4 space-y-2 text-xs sm:text-[13px] text-slate-600">
        <p className="flex items-center gap-2">
          <CalendarDays size={14} className="text-slate-300 shrink-0" />
          <span className="font-medium text-slate-700">Due:</span>
          <span className={!isCompleted && isLate ? "text-rose-600 font-semibold" : !isCompleted && isSoon ? "text-amber-600 font-semibold" : ""}>
            {formatDate(record.dueDate)}
          </span>
        </p>
        <p className="flex items-center gap-2">
          <Flag size={14} className="text-slate-300 shrink-0" />
          <span className="font-medium text-slate-700">FY:</span> {record.financialYear || "—"}
        </p>
        <p className="flex items-center gap-2">
          <User size={14} className="text-slate-400 shrink-0" />
          {record.assignedStaff?.name ? (
            record.assignedStaff.name
          ) : (
            <span className="font-medium text-amber-700">Unassigned</span>
          )}
        </p>
      </div>

      {!isCompleted && (
        <div className="mt-3 sm:mt-4 pt-3 sm:pt-4 border-t border-slate-100 flex flex-wrap gap-2">
          {status === "PENDING" && (
            <Button size="sm" variant="secondary" onClick={() => changeStatus("IN_PROGRESS")} loading={updating}>
              <PlayCircle size={14} /> Start
            </Button>
          )}
          {status === "IN_PROGRESS" && (
            <Button size="sm" variant="secondary" onClick={() => changeStatus("PENDING")} loading={updating}>
              <RotateCcw size={13} /> Reset
            </Button>
          )}
          <Button size="sm" variant="success" onClick={() => changeStatus("COMPLETED")} loading={updating}>
            <CheckCircle2 size={14} /> Complete
          </Button>
          {record.clientId?.phone && (
            <WhatsAppButton
              phone={record.clientId.phone}
              client={record.clientId}
              clientId={record.clientId._id}
              message={generateDocumentRequestMessage({
                client: record.clientId,
                documents: [],
                period: record.financialYear || record.period || null,
              })}
              label="Request docs"
              messageType="DOCUMENT_REQUEST"
              iconOnly
            />
          )}
        </div>
      )}

      {isCompleted && onStatusChange && (
        <div className="mt-3 sm:mt-4 pt-3 sm:pt-4 border-t border-slate-100">
          <Button
            size="sm"
            variant="ghost"
            onClick={() => changeStatus("IN_PROGRESS")}
            loading={updating}
            className="text-slate-500"
          >
            <RotateCcw size={13} /> Undo (mark in progress)
          </Button>
        </div>
      )}
    </div>
  );
}
