import Compliance from "@/models/Compliance";

const MONTH_NAMES = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

function startOfDay(date) {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
}

/**
 * Next occurrence of `dayOfMonth` strictly after today.
 * e.g. nextMonthlyDue(20) => the 20th of this or next month, whichever is ahead.
 */
function nextDueOn(dayOfMonth) {
  const now = new Date();
  const candidate = new Date(now.getFullYear(), now.getMonth(), dayOfMonth);
  if (candidate <= now) candidate.setMonth(candidate.getMonth() + 1);
  return candidate;
}

/**
 * Quarterly TDS -> 31 Jul / 31 Oct / 31 Jan / 30 Apr (last day of the month
 * following the quarter end), picking the earliest occurrence still ahead.
 */
function nextQuarterlyTdsDue() {
  const now = new Date();
  const candidates = [
    { month: 3, day: 30 }, // TDS Q1 (Apr–Jun) -> 30 Apr
    { month: 6, day: 31 }, // TDS Q2 (Jul–Sep) -> 31 Jul
    { month: 9, day: 31 }, // TDS Q3 (Oct–Dec) -> 31 Oct
    { month: 0, day: 31 }, // TDS Q4 (Jan–Mar) -> 31 Jan
  ];
  for (const year of [now.getFullYear(), now.getFullYear() + 1]) {
    for (const { month, day } of candidates) {
      const due = new Date(year, month, day, 0, 0, 0, 0);
      if (due > now) return due;
    }
  }
  return null;
}

function formatMonthYear(date) {
  return `${MONTH_NAMES[date.getMonth()]} ${date.getFullYear()}`;
}

function fyLabel(startYear) {
  return `${startYear}-${String((startYear + 1) % 100).padStart(2, "0")}`;
}

/**
 * FY label for a date. Apr 2026 – Mar 2027 => "2026-27". The same convention
 * used by the existing recurring-rollforward logic.
 */
function fyForDate(date) {
  const year = date.getMonth() >= 3 ? date.getFullYear() : date.getFullYear() - 1;
  return fyLabel(year);
}

/**
 * Builds the default compliance calendar for a freshly added client.
 *
 * Only creates ONE upcoming occurrence per filing type (autoGenerated + a
 * recurrence), so completing a filing rolls the next one forward via the
 * existing generateNextCompliance sweep. This keeps the compliance list clean
 * instead of pre-filling a whole year of records.
 *
 * Applicability is derived purely from the client (category + GSTIN), so
 * nothing extra is shown to the user or added to the UI.
 */
export function buildComplianceCalendar(client) {
  const clientId = client._id || client.id;
  if (!clientId) return [];
  const companyId = client.companyId;
  const category = client.category;
  const hasGst = Boolean(String(client.gstin || "").trim());
  const assignedStaff = client.assignedStaff || null;
  const createdBy = client.createdBy || null;

  const templates = [];

  const addGstMonthly = (type, dayOfMonth) => {
    templates.push({
      type,
      category: "GST",
      recurrence: "MONTHLY",
      deps: hasGst,
      build: () => {
        const due = nextDueOn(dayOfMonth);
        const period = new Date(due.getFullYear(), due.getMonth() - 1, 1);
        return {
          period: formatMonthYear(period),
          financialYear: fyForDate(period),
          dueDate: due,
        };
      },
    });
  };

  const addGstAnnual = () => {
    templates.push({
      type: "GSTR-9",
      category: "GST",
      recurrence: "ANNUAL",
      deps: hasGst,
      build: () => {
        const now = new Date();
        let due = new Date(now.getFullYear(), 11, 31, 0, 0, 0, 0);
        if (due <= now) due = new Date(now.getFullYear() + 1, 11, 31, 0, 0, 0, 0);
        return { period: `FY ${fyLabel(due.getFullYear() - 1)}`, financialYear: fyLabel(due.getFullYear() - 1), dueDate: due };
      },
    });
  };

  const addItr = () => {
    templates.push({
      type: "ITR",
      category: "Income Tax",
      recurrence: "ANNUAL",
      deps: category !== "Other",
      build: () => {
        const now = new Date();
        let due = new Date(now.getFullYear(), 6, 31, 0, 0, 0, 0);
        if (due <= now) due = new Date(now.getFullYear() + 1, 6, 31, 0, 0, 0, 0);
        return { period: `FY ${fyLabel(due.getFullYear() - 1)}`, financialYear: fyLabel(due.getFullYear() - 1), dueDate: due };
      },
    });
  };

  const addTds = () => {
    templates.push({
      type: "TDS Return",
      category: "TDS",
      recurrence: "QUARTERLY",
      deps: ["Proprietor", "Partnership", "Pvt Ltd", "LLP"].includes(category),
      build: () => {
        const due = nextQuarterlyTdsDue();
        const quarterIndex = Math.floor(((due.getMonth() + 6) % 12) / 3) + 1;
        const fy = due.getMonth() === 3 ? fyLabel(due.getFullYear() - 1) : fyForDate(due);
        return { period: `Q${quarterIndex} FY ${fy}`, financialYear: fy, dueDate: due };
      },
    });
  };

  const addRoc = () => {
    templates.push({
      type: "ROC Filing",
      category: "ROC",
      recurrence: "ANNUAL",
      deps: ["Pvt Ltd", "LLP"].includes(category),
      build: () => {
        const now = new Date();
        let due = new Date(now.getFullYear(), 9, 31, 0, 0, 0, 0);
        if (due <= now) due = new Date(now.getFullYear() + 1, 9, 31, 0, 0, 0, 0);
        return { period: `FY ${fyLabel(due.getFullYear() - 1)}`, financialYear: fyLabel(due.getFullYear() - 1), dueDate: due };
      },
    });
  };

  addGstMonthly("GSTR-1", 11);
  addGstMonthly("GSTR-3B", 20);
  addGstAnnual();
  addItr();
  addTds();
  addRoc();

  return templates
    .filter((t) => t.deps)
    .map((t) => {
      const { period, financialYear, dueDate } = t.build();
      return {
        companyId,
        clientId,
        type: t.type,
        category: t.category,
        period,
        financialYear,
        dueDate,
        assignedStaff,
        status: "PENDING",
        priority: "MEDIUM",
        recurrence: t.recurrence,
        autoGenerated: true,
        createdBy,
      };
    });
}

/**
 * Persists the calendar for one client. Safe to call extra times — duplicate
 * occurrences are rejected by the unique auto-generated index and skipped.
 */
export async function applyComplianceCalendar(client) {
  const docs = buildComplianceCalendar(client);
  if (!docs.length) return 0;
  try {
    await Compliance.insertMany(docs, { ordered: false });
    return docs.length;
  } catch (err) {
    if (err?.code !== 11000) console.error("applyComplianceCalendar failed:", err.message);
    return docs.length;
  }
}