import Compliance from "@/models/Compliance";
import User from "@/models/User";
import Notification from "@/models/Notification";
import { createNotification } from "@/lib/notifications";

const DUE_SOON_DAYS = 7;
const RECURRENCE_STEP_MONTHS = { MONTHLY: 1, QUARTERLY: 3, ANNUAL: 12 };

function addMonths(date, months) {
  const d = new Date(date);
  const day = d.getDate();
  d.setMonth(d.getMonth() + months);
  if (d.getDate() !== day) d.setDate(0);
  return d;
}

function startOfDay(date) {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
}

/**
 * Whole calendar days between today and the due date.
 * Due today => 0, yesterday => -1, tomorrow => 1.
 */
export function calendarDaysLeft(dueDate) {
  const due = startOfDay(dueDate).getTime();
  const today = startOfDay(new Date()).getTime();
  return Math.round((due - today) / (24 * 60 * 60 * 1000));
}

export function computeNextDueDate(dueDate, recurrence) {
  const step = RECURRENCE_STEP_MONTHS[recurrence];
  if (!step) return null;
  return addMonths(new Date(dueDate), step);
}

/**
 * When a recurring filing is completed, auto-create the NEXT occurrence
 * so the CRM always shows the upcoming due date. Skips if it already exists.
 */
export async function generateNextCompliance(record) {
  try {
    if (!record || !record.recurrence || record.recurrence === "NONE") return null;

    const step = RECURRENCE_STEP_MONTHS[record.recurrence];
    const now = new Date();
    // ALWAYS advance by at least one full cycle first — completing a filing
    // early (before its due date) must never produce a clone of itself.
    let next = addMonths(new Date(record.dueDate), step);

    let guard = 0;
    while (startOfDay(next) <= startOfDay(now) && guard < 240) {
      next = addMonths(next, step);
      guard++;
    }
    if (next <= now) return null;

    const duplicate = await Compliance.findOne({
      clientId: record.clientId,
      type: record.type,
      category: record.category,
      dueDate: next,
      _id: { $ne: record._id },
    }).lean();
    if (duplicate) return null;

    let created;
    try {
      created = await Compliance.create({
        clientId: record.clientId,
        type: record.type,
        category: record.category,
        period: record.period,
        financialYear: computeFinancialYear(next),
        dueDate: next,
        assignedStaff: record.assignedStaff || null,
        priority: record.priority,
        recurrence: record.recurrence,
        description: record.description,
        status: "PENDING",
        autoGenerated: true,
        createdBy: record.createdBy,
      });
    } catch (err) {
      // Unique index guard — another concurrent request created it first.
      if (err?.code === 11000) return null;
      throw err;
    }

    await notifyRecipients(created, {
      type: "COMPLIANCE_DUE",
      title: "Next filing scheduled",
      message: `${created.type} (${created.recurrence.toLowerCase()}) is due on ${next.toLocaleDateString("en-IN")}.`,
    });

    return created;
  } catch (error) {
    console.error("generateNextCompliance failed:", error.message);
    return null;
  }
}

/**
 * India FY runs Apr–Mar: Apr 2026 – Mar 2027 => "2026-27".
 */
function computeFinancialYear(dueDate) {
  const d = new Date(dueDate);
  const year = d.getMonth() >= 3 ? d.getFullYear() : d.getFullYear() - 1;
  return `${year}-${String((year + 1) % 100).padStart(2, "0")}`;
}

/**
 * Notifies the assigned staff member; unassigned filings go to ALL admins.
 */
async function notifyRecipients(record, payload) {
  if (record.assignedStaff) {
    await createNotification({ userId: record.assignedStaff, ...payload });
    return;
  }
  // Only admins of the same company receive unassigned-filing notifications.
  const filter = { role: "admin" };
  if (record.companyId) filter.companyId = record.companyId;
  const admins = await User.find(filter).select("_id").lean();
  for (const admin of admins) {
    await createNotification({ userId: admin._id, ...payload });
  }
}

/**
 * Safety net: makes sure every recently-completed recurring filing has its
 * NEXT occurrence created — covers records completed before this logic
 * existed, or where generation failed. Idempotent (skips duplicates).
 * Also removes duplicate auto-generated clones left by older versions.
 */
let inflightRollforward = null;
let lastRollforwardAt = 0;

export function ensureRecurringRollforward() {
  // Single-flight + cooldown: many API calls fire in parallel on page load;
  // they must share one execution or races can create duplicates.
  if (inflightRollforward) return inflightRollforward;
  if (Date.now() - lastRollforwardAt < 10_000) return Promise.resolve();
  inflightRollforward = _ensureRecurringRollforward()
    .catch((error) => console.error("ensureRecurringRollforward failed:", error.message))
    .finally(() => {
      lastRollforwardAt = Date.now();
      inflightRollforward = null;
    });
  return inflightRollforward;
}

async function _ensureRecurringRollforward() {
  try {
    await dedupeAutoGenerated();

    const cutoff = new Date(Date.now() - 400 * 24 * 60 * 60 * 1000);
    const completed = await Compliance.find({
      status: "COMPLETED",
      recurrence: { $in: Object.keys(RECURRENCE_STEP_MONTHS) },
      completedAt: { $gte: cutoff },
    })
      .sort({ completedAt: -1 })
      .limit(50)
      .lean();

    for (const record of completed) {
      const next = computeNextDueDate(record.dueDate, record.recurrence);
      if (!next || next <= new Date()) continue;
      const exists = await Compliance.exists({
        clientId: record.clientId,
        type: record.type,
        category: record.category,
        dueDate: { $gte: next },
        status: { $ne: "COMPLETED" },
        _id: { $ne: record._id },
      });
      if (!exists) await generateNextCompliance(record);
    }
  } catch (error) {
    console.error("ensureRecurringRollforward failed:", error.message);
  }
}

/**
 * Removes extra auto-generated copies that share client + type + category +
 * due date (legacy bug cloned filings completed before their due date).
 * Keeps the oldest copy, deletes the rest.
 */
async function dedupeAutoGenerated() {
  try {
    const dups = await Compliance.aggregate([
      { $match: { autoGenerated: true } },
      {
        $group: {
          _id: { clientId: "$clientId", type: "$type", category: "$category", dueDate: "$dueDate" },
          ids: { $push: "$_id" },
          count: { $sum: 1 },
        },
      },
      { $match: { count: { $gt: 1 } } },
    ]);
    for (const dup of dups) {
      const [, ...remove] = dup.ids; // keep the first-created copy
      await Compliance.deleteMany({ _id: { $in: remove } });
    }
  } catch (error) {
    console.error("dedupeAutoGenerated failed:", error.message);
  }
}

/**
 * Creates reminders for every uncompleted filing that is:
 *  - due within the next DUE_SOON_DAYS days, or
 *  - already overdue.
 * One notification per RECORD + TYPE + USER (deduplicated per recipient,
 * so every admin/staff member gets their own notification).
 * Notifies assigned staff; unassigned filings go to all admins.
 *
 * Single-flight + cooldown: the dashboard and compliance pages fire several
 * parallel API calls, each triggering this sweep. Sharing one run and skipping
 * re-runs within a window keeps page loads fast.
 */
let inflightReminders = null;
let lastRemindersAt = 0;

export function refreshComplianceReminders() {
  if (inflightReminders) return inflightReminders;
  if (Date.now() - lastRemindersAt < 10_000) return Promise.resolve();
  inflightReminders = _refreshComplianceReminders()
    .catch((error) => console.error("refreshComplianceReminders failed:", error.message))
    .finally(() => {
      lastRemindersAt = Date.now();
      inflightReminders = null;
    });
  return inflightReminders;
}

async function _refreshComplianceReminders() {
  try {
    const now = new Date();
    const soonCutoff = new Date(now.getTime() + DUE_SOON_DAYS * 24 * 60 * 60 * 1000);

    const records = await Compliance.find({
      status: { $ne: "COMPLETED" },
      dueDate: { $lte: soonCutoff },
    })
      .populate("clientId", "name")
      .limit(200)
      .lean();

    for (const r of records) {
      const daysLeft = calendarDaysLeft(r.dueDate);
      const overdue = daysLeft < 0;
      const nType = overdue ? "COMPLIANCE_OVERDUE" : "COMPLIANCE_DUE_SOON";

      const clientName = r.clientId?.name || "client";
      const when = overdue
        ? `was due on ${new Date(r.dueDate).toLocaleDateString("en-IN")} (${Math.abs(daysLeft)} day(s) ago)`
        : `is due on ${new Date(r.dueDate).toLocaleDateString("en-IN")} (${daysLeft === 0 ? "TODAY" : `in ${daysLeft} day(s)`})`;

      const payload = {
        type: nType,
        title: overdue ? "Filing overdue" : daysLeft === 0 ? "Filing due TODAY" : "Filing due soon",
        message: `${r.type} for ${clientName} ${when}.`,
        entityType: "Compliance",
        entityId: r._id,
      };

      if (r.assignedStaff) {
        const alreadySent = await Notification.exists({
          userId: r.assignedStaff,
          entityType: "Compliance",
          entityId: r._id,
          type: nType,
        });
        if (!alreadySent) {
          await createNotification({ userId: r.assignedStaff, ...payload });
        }
      } else {
        const filter = { role: "admin" };
        if (r.companyId) filter.companyId = r.companyId;
        const admins = await User.find(filter).select("_id").lean();
        for (const admin of admins) {
          const alreadySent = await Notification.exists({
            userId: admin._id,
            entityType: "Compliance",
            entityId: r._id,
            type: nType,
          });
          if (!alreadySent) {
            await createNotification({ userId: admin._id, ...payload });
          }
        }
      }
    }
  } catch (error) {
    console.error("refreshComplianceReminders failed:", error.message);
  }
}
